### ISSUE TITLE
404 link in README

### ISSUE THREAD

**Issue by docs-product** [Azure-Samples/iot-hub-how-to-kepware-edge#3]
In the `README.md`, the link to instructions is a 404:

```
per their own [instructions](https://www.kepware.com/getattachment/c93c65df-57ea-4e9c-a1e0-2e9a34381d54/mqtt-client-and-microsoft-azure-iot.pdf)
```

**Comment by docs-product** [comment]
@stevebus - can you help look into this?

**Comment by stevebus** [comment]
yes, looks like they moved the location of the instructions.   I'll update the link.  thanks for finding and opening the issue.

**Comment by stevebus** [comment]
This is fixed now.  Do you want to verify and close?  or want me to close?
